### ISSUE TITLE
in Grid we MUST be able to export filtered results

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#12]
Until then, it was not possible to export only the selected items of a Grid (even in 1.6).

Now the search will be done using POST action, we have access to the selected items... time to make the export system more extensible and able to export only a selection !

**Comment by sarjon** [comment]
@mickaelandrieu here's how it could be improved.

Lets say we want to export logs. What we could do is:

```php
public function exportAction(LogsFilters $filters) {
    $logsDataProvider = $this->get('prestashop.core.grid.data_provider.log');
    $logsData = $logsDataProvider->getData($filters);

    return new CsvResponse($logsData->getRows());
}
```
At the moment `$filters` implements `PrestaShop\PrestaShop\Core\Grid\Search\SearchCriteriaInterface`, but the problem is that `offset` and `limit` are not ignored by data provider, so exported results are not complete.

What we could do is update `SearchCriteriaInterface` interface with:

```diff
/**
- * @return int
+ * @return int|null Return offset or null to disable offset
 */
public function getOffset();
```

And do the same for `getLimit()`. In that case data provider would know to ignore offset and limit when `null` is returned. 

This is how `exportAction` could be implemented after update:

```php
// LogsController.php

public function exportAction(LogsFilters $filters) {
    $exportFilters = new ExportSearchCriteria($filters);

    $logsDataProvider = $this->get('prestashop.core.grid.data_provider.log');
    $logsData = $logsDataProvider->getData($exportFilters);

    return new CsvResponse($logsData->getRows());
}

// ExportSearchCriteria.php

final class ExportSearchCriteria implements SearchCriteriaInterface
{
    private $criteria;

    public function __construct(SearchCriteriaInterface $criteria)
    {
        $this->criteria = $criteria;
    }

    public function getOffset()
    {
        return null;    // make sure offset is always ignored, same could go for getLimit()
    }

    public function getFilters()
    {
        return $this->criteria->getFilters();    // we still want to use original filters so we return them
    }
}
```
