### ISSUE TITLE
Introduce Encore for new-theme webpack configuration

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/prestafony-project#65]
Encore provides clean API, but still allows to configure webpack as you normally would, so why not adding it?

**Comment by PierreRambaud** [comment]
Great Idea!

**Comment by mickaelandrieu** [comment]
not a great idea at all, but @eternoendless is far better than me to explain why.

TLDR; won't happens, I'm against it and @eternoendless too :p

**Comment by sarjon** [comment]
no problem, but please, explain. :pray:

**Comment by mickaelandrieu** [comment]
my explanation: it's a layer on top of webpack, and it won't evolve as fast as Webpack.

It's developed by PHP developers, with PHP-like api in mind, which is wrong as the frontend is mostly managed by javascript developers. This add no real value, except some sugar that you can enjoy once in your project (the beginning, when you setup) and then you forgot about it.

But, because few PHP developers master Webpack ... and less PHP developers master Symfony Encore, you have introduced what we can call technical debt in your project ... for free.

More, because you rely on an extra layer, you can't update it easily as you are not in charge of maintaining it: this is something we try to avoid for non-established libraries in PrestaShop.

My 2 cents :trollface:

**Comment by sarjon** [comment]
@mickaelandrieu thanks! closing.

**Comment by mickaelandrieu** [comment]
I'm not the only one to decide and I'd like to know why do you want to introduce it?

**Comment by sarjon** [comment]
main reason for me:
> Encore provides clean API, but still allows to configure webpack as you normally would

And regarding:
> Only few PHP developers master Webpack ... and less PHP developers master Symfony Encore

I see PHP developers are more comfortable using tools like Encore or Laravel Mix than configuring Webpack themselves, but as you said, it may not be that easy for frontend devs. :)
