### ISSUE TITLE
Use Hooks to extend configuration forms

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/prestafony-project#69]
At the moment there's hook in `FormHandler` that allows to extend configuration forms. Lets take Administration page as example, we have `actionAdministrationPageForm`. This hook allows multiple modules to extends form, which is great. 

By default, there is `{{ form_rest(form) }}` in administration template which renders form with extended inputs, but it does not look good in most cases.

To render custom fields that looks however you want, you would have to extend administration template and override some block and that would work, but...

While multiple modules can extends form, only one module can override same template to customize form rendering and thats an issue.

What if in addition of having `{{ form_rest(form) }}` we would have this:

```twig
{{ form_start(form) }}

    {# Default form rendering #}
    {# ... #}

    {# Then let modules render their fields #}
    {{ renderhook('displayAdministrationPageForm', { 'form': form }) }}

    {# And only then render the rest of the form if theres anything left #}
    {{ form_rest(form) }}

{{ form_end(form) }}
```

In this case, multiple modules can both extend & render their fields. :)

_NOTE: I did not test it yet and I dont know if that would actually work or not._

**Comment by mickaelandrieu** [comment]
I wanted to do that too but if you don't update the real Symfony form you can't really validate it. It's not like in 1.6, everything sent in POST is not mapped to the table, and regarding CQRS we try to introduce this will become harder and harder to do it.

How can we add new fields to a form action created with CQRS approach?

**Comment by sarjon** [comment]
> if you don't update the real Symfony form you can't really validate it

what do you mean?

> Also, I don't want to use hooks to manage the display

Well, there are a lot of _display_ type hooks and seems that they arent going anywhere any time soon. Developers are already used to rendering content via hooks, so imo its not that bad solution at this point maybe? :) And we dont have a good alternative now, right? :/

> How can we add new fields to a form action created with CQRS approach?

As far as I understand, CQRS has nothing to to with forms building. If we follow this (https://github.com/PrestaShop/prestafony-project/issues/66 and it seems that @eternoendless has similar idea) approach for form management you will see that hooks to extend forms are dispatched not in Commands or Queries layer but before that, so i think it should be similar as it is currently with Configuration forms management, it should not change much. I could be wrong, so I think @eternoendless could give more insights here.

I really want developers to be able to extend forms in a way that the fields are not "just rendered", but that it looks good and can be customized by multiple modules according to their needs. :)

**Comment by mickaelandrieu** [comment]
> what do you mean?

I mean that if people build form input on their own without respect the expected name, it wont works and they will complain as hell it's a bug when it's not, because they are not supposed to write HTML here but use the form builder :/

> so imo its not that bad solution

It is! you have no control on what is displayed as you can't figure out which modules will add display before or after you :/

For the forms, they have to rely on the "Symfony" way to do it, open a display hook here will create more bugs than solutions: this is why I stick to my plan.

In the end, there will be no display hooks or at least not on their current form:

- we can't validate a string content
- we can't control HTML validity
- this doesn't solve the issue with modules conflicting with each other

Regarding the rendering of the fields we add to the form, I think it can be improved at the "form theme" level, so there will be almost no need to override the template, "and" we could declare a specific template for every form field like we already do for the Grid component.
